### ISSUE TITLE
Example demo page

### ISSUE THREAD

**Issue by pcanterini** [sadiqevani/react-modal-box#2]
The example is pretty basic but would be nice to have a live demo so people don't have to clone to check it out.

I've created an [example branch](https://github.com/pcanterini/react-modal-box/tree/demo-page#api) too if you want to check it out.

[This gist](https://gist.github.com/cobyism/4730490) has good info on how to add it from the master branch, just pointing to the examples folder, if you need more info.

**Comment by sadiqevani** [comment]
@pcanterini thank you, will do :)

**Comment by sadiqevani** [comment]
@pcanterini its done. I am closing the issue now. Thank you.
